name: React CI/CD Pipeline

on:
  push:
    branches:
      - main       # run on push to main branch
  pull_request:
    branches:
      - main       # also run on PRs to main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test -- --watchAll=false

    - name: Build React app
      run: npm run build

  # Optional deployment step - uncomment and customize if needed
  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

